CREATE TABLE IF NOT EXISTS withholds (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(255) NOT NULL,
    number character varying(255) NOT NULL,
    date date NOT NULL,
    identification_type character varying(255) NOT NULL,
    identification character varying(255) NOT NULL,
    legal_name character varying(255) NOT NULL,
    access_key character varying(255) NOT NULL,
    fiscal_period character varying(255) NOT NULL,
    related character varying(255),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT withholds_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_withholds_code_number ON withholds (code, number);
CREATE UNIQUE INDEX IF NOT EXISTS ix_withholds_access_key ON withholds (access_key);

CREATE TABLE IF NOT EXISTS withholds_support (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code_support character varying(255) NOT NULL,
    code_document_support character varying(255) NOT NULL,
    number_document_support character varying(255) NOT NULL,
    date_document_support date NOT NULL,
    authorization_document_support character varying(255) NOT NULL,
    total_without_taxes numeric(38,2) NOT NULL,
    total numeric(38,2) NOT NULL,
    withhold_id integer NOT NULL,
    CONSTRAINT withholds_support_pkey PRIMARY KEY (id),
    CONSTRAINT fk_withholds_support_withholds FOREIGN KEY (withhold_id)
        REFERENCES withholds (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS withholds_detail (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    line integer NOT NULL,
    tax_code character varying(255) NOT NULL,
    withhold_code character varying(255) NOT NULL,
    base_value numeric(38,2) NOT NULL,
    percentage numeric(38,2) NOT NULL,
    withholded_value numeric(38,2) NOT NULL,
    withhold_support_id integer NOT NULL,
    CONSTRAINT withholds_detail_pkey PRIMARY KEY (id),
    CONSTRAINT fk_withholds_detail_support FOREIGN KEY (withhold_support_id)
        REFERENCES withholds_support (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS withholds_document_taxes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    tax_code character varying(255) NOT NULL,
    percentage_code character varying(255) NOT NULL,
    tax_base numeric(38,2) NOT NULL,
    tax_iva numeric(38,2) NOT NULL,
    value numeric(38,2) NOT NULL,
    withhold_support_id integer NOT NULL,
    CONSTRAINT withholds_document_taxes_pkey PRIMARY KEY (id),
    CONSTRAINT fk_withholds_document_taxes_support FOREIGN KEY (withhold_support_id)
        REFERENCES withholds_support (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v_assets (
    id character varying(255) NOT NULL,
    name character varying(255),
    value character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_credit_notes (
    total numeric(38,2),
    total_without_taxes numeric(38,2),
    date date,
    updated_date_document date,
    id bigint NOT NULL,
    access_key character varying(255),
    address character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    reason character varying(255),
    sequence character varying(255),
    updated_code_document character varying(255),
    updated_number_document character varying(255)
);


DROP VIEW IF EXISTS v_ele_credit_notes_detail;
CREATE VIEW v_ele_credit_notes_detail AS
    SELECT
        dd.id::bigint id,
        d.code,
        d.number,
        dd.product_code                AS principal_code,
        dd.line::bigint                AS line,
        dd.product_name                AS name,
        dd.quantity,
        dd.unit_price,
        dd.tax_code,
        dd.tax_iva,
        dd.value_iva,
        dd.discount,
        dd.total_without_tax           AS total_price_without_tax
    FROM documents_detail dd
    JOIN documents d ON d.id = dd.document_id;

CREATE TABLE IF NOT EXISTS v_ele_debit_notes (
    total numeric(38,2),
    total_without_taxes numeric(38,2),
    date date,
    updated_date_document date,
    id bigint NOT NULL,
    access_key character varying(255),
    address character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    sequence character varying(255),
    updated_code_document character varying(255),
    updated_number_document character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_debit_notes_detail (
    value numeric(38,2),
    line bigint,
    id bigint NOT NULL,
    code character varying(255),
    number character varying(255),
    reason character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_delivery_notes (
    date date,
    date_end_transport date,
    date_start_transport date,
    id bigint NOT NULL,
    access_key character varying(255),
    address_start character varying(255),
    carrier_identification character varying(255),
    carrier_identification_type character varying(255),
    carrier_legal_name character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    number character varying(255),
    observation character varying(255),
    plate character varying(255),
    sequence character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_delivery_notes_receiver (
    date_document_support date,
    line bigint,
    id bigint NOT NULL,
    address character varying(255),
    authorization_document_support character varying(255),
    code character varying(255),
    code_document_support character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    number_document_support character varying(255),
    transfer_reason character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_delivery_notes_receiver_detail (
    quantity numeric(38,2),
    line bigint,
    id bigint NOT NULL,
    code character varying(255),
    name character varying(255),
    number character varying(255),
    principal_code character varying(255)
);

DROP VIEW IF EXISTS v_ele_establishments;
CREATE VIEW v_ele_establishments AS
    SELECT 
        e.id::bigint as id,
        t.identification,
        e.code, 
        e.business_name, 
        e.address,
        CASE 
	        WHEN e.is_principal = true THEN 'Principal'
	        ELSE 'BranchOffice'
    	END AS principal        
    FROM establishments e join taxpayers t
	on t.id = e.taxpayer_id;

CREATE TABLE IF NOT EXISTS v_ele_general_observations (
    id integer NOT NULL,
    name character varying(255),
    value character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_information (
    id integer NOT NULL,
    identification character varying(255),
    name character varying(255),
    value character varying(255)
);

DROP VIEW IF EXISTS v_ele_invoices cascade;
CREATE VIEW v_ele_invoices AS
    select
        i.id::bigint id,
        i.code,
        i.number,
        '01' as code_document,
        substr(i.number, 1, 3) as establishment,
        substr(i.number, 4, 3) as emission_point,
        substr(i.number, 7, 15) as sequence,
        i.date,
        sum(d.total_without_tax) as total_without_taxes,
        sum(d.discount) discount,
        sum(d.total) total,
        0::numeric tip,
        i.identification_type,
        i.identification,
        i.legal_name,
        i.address,
        i.delivery_note,
        (
        select
            e.address
        from
            establishments e
        where
            e.code = substr(i.number, 1, 3)) establishment_address,
        i.access_key
    from
        documents i
    join documents_detail d
    on
        i.id = d.document_id
    group by
        i.id,
        i.code,
        i.number,
        substr(i.number, 1, 3),
        substr(i.number, 4, 3),
        substr(i.number, 7, 15),
        i.date,
        i.identification_type,
        i.identification,
        i.legal_name,
        i.address,
        i.delivery_note,
        i.access_key;

DROP VIEW IF EXISTS v_ele_invoices_detail;
CREATE VIEW v_ele_invoices_detail AS
    SELECT
        d.id::bigint id,
        d.code,
        d.number,
        dd.product_code                AS principal_code,
        dd.line::bigint                AS line,
        dd.product_name                AS name,
        dd.quantity,
        dd.unit,
        dd.unit_price,
        dd.tax_code,
        dd.tax_iva,
        dd.value_iva,
        dd.discount,
        dd.total_without_tax           AS total_price_without_tax
    FROM documents_detail dd
    JOIN documents d ON d.id = dd.document_id;        

DROP VIEW IF EXISTS v_ele_liquidations cascade;
CREATE VIEW v_ele_liquidations AS
    SELECT
        i.id::bigint id,
        i.code,
        i.number,
        '03' AS code_document,
        substr(i.number, 1, 3) AS establishment,
        substr(i.number, 4, 3) AS emission_point,
        substr(i.number, 7, 15) AS sequence,
        i.date,
        sum(d.total_without_tax) AS total_without_taxes,
        sum(d.discount) AS discount,
        sum(d.total) AS total,
        i.identification_type,
        i.identification,
        i.legal_name,
        i.address,
        (
        SELECT e.address FROM establishments e
        WHERE e.code = substr(i.number, 1, 3)) AS establishment_address,
        i.access_key
    FROM documents i
    JOIN documents_detail d ON i.id = d.document_id
    GROUP BY
        i.id, i.code, i.number,
        substr(i.number, 1, 3), substr(i.number, 4, 3), substr(i.number, 7, 15),
        i.date, i.identification_type, i.identification, i.legal_name,
        i.address, i.access_key;

DROP VIEW IF EXISTS v_ele_liquidations_detail;
CREATE VIEW v_ele_liquidations_detail AS
    SELECT
        dd.id::bigint id,
        d.code,
        d.number,
        dd.product_code                AS principal_code,
        dd.line::bigint                AS line,
        dd.product_name                AS name,
        dd.quantity,
        dd.unit,
        dd.unit_price,
        dd.tax_code,
        dd.tax_iva,
        dd.value_iva,
        dd.discount,
        dd.total_without_tax           AS total_price_without_tax
    FROM documents_detail dd
    JOIN documents d ON d.id = dd.document_id;

DROP VIEW IF EXISTS v_ele_liquidations_taxes;
CREATE VIEW v_ele_liquidations_taxes AS
    SELECT
        t.id::bigint id,
        d.code,
        d.number,
        dd.product_code                AS principal_code,
        dd.line::bigint                AS line,
        t.tax_code,
        t.tax_code_percentage          AS percentage_code,
        t.base                         AS tax_base,
        t.tax_value                    AS tax_iva,
        t.value
    FROM documents_detail_taxes t
    JOIN documents_detail dd ON dd.id = t.document_detail_id
    JOIN documents d ON d.id = dd.document_id;

DROP VIEW IF EXISTS v_ele_payments;
CREATE VIEW v_ele_payments AS
    SELECT
        p.id::bigint id,
        d.code,
        d.number,
        p.code                         AS way_pay,
        CASE p.code
            WHEN '01' THEN 'SIN UTILIZACION DEL SISTEMA FINANCIERO'
            ELSE 'OTROS CON UTILIZACION DEL SISTEMA FINANCIERO'
        END                            AS name,
        p.total,
        p.deadline                     AS payment_deadline,
        p.unit_time
    FROM documents_payment p
    JOIN documents d ON d.id = p.document_id;

CREATE TABLE IF NOT EXISTS v_ele_report_credit_notes (
    total numeric(38,2),
    date date,
    id bigint NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_debit_notes (
    total numeric(38,2),
    date date,
    id bigint NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_delivery_notes (
    total numeric(38,2),
    date date,
    id bigint NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

DROP VIEW IF EXISTS v_ele_report_invoices;
CREATE VIEW v_ele_report_invoices AS
SELECT 
    j.id::bigint AS id,
    j.code AS code,
    j.number AS number,
    j.access_key AS access_key,
    j.date AS date,
    j.total AS total,
    j.identification AS identification,
    j.legal_name AS legal_name,
    (SELECT i.value
     FROM v_ele_information i
     WHERE i.name = 'Email'
       AND i.identification = j.identification
     LIMIT 1) AS email,
    COALESCE(
        (SELECT e.status 
         FROM ele_documents e 
         WHERE e.code = j.code 
           AND e.number = j.number
        ), 
        'NO ENVIADO'
    ) AS status
FROM 
    v_ele_invoices j
ORDER BY 
    j.number DESC;

CREATE TABLE IF NOT EXISTS v_ele_report_liquidations (
    total numeric(38,2),
    date date,
    id bigint NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

DROP VIEW IF EXISTS v_ele_report_withholds;
CREATE VIEW v_ele_report_withholds AS
SELECT
    w.id::bigint AS id,
    w.code AS code,
    w.number AS number,
    w.access_key AS access_key,
    w.date AS date,
    COALESCE(
        (SELECT sum(d.withholded_value)
         FROM withholds_detail d
         JOIN withholds_support s ON s.id = d.withhold_support_id
         WHERE s.withhold_id = w.id
        ), 0) AS total,
    w.identification AS identification,
    w.legal_name AS legal_name,
    (SELECT i.value
     FROM v_ele_information i
     WHERE i.name = 'Email'
       AND i.identification = w.identification
     LIMIT 1) AS email,
    COALESCE(
        (SELECT e.status
         FROM ele_documents e
         WHERE e.code = w.code
           AND e.number = w.number
        ),
        'NO ENVIADO'
    ) AS status
FROM
    withholds w
ORDER BY
    w.number DESC;

DROP VIEW IF EXISTS v_ele_taxes_detail;
CREATE VIEW v_ele_taxes_detail AS
    SELECT
        t.id::bigint id,
        d.code,
        d.number,
        dd.product_code                AS principal_code,
        dd.line::bigint                AS line,
        t.tax_code,
        t.tax_code_percentage          AS percentage_code,
        t.base                         AS tax_base,
        t.tax_value                    AS tax_iva,
        t.value
    FROM documents_detail_taxes t
    JOIN documents_detail dd ON dd.id = t.document_detail_id
    JOIN documents d ON d.id = dd.document_id;

CREATE OR REPLACE VIEW v_ele_taxpayer AS
    SELECT 
        id, 
        identification, 
        legal_name, 
        forced_accounting, 
        special_taxpayer, 
        retention_agent, 
        rimpe as regime
    FROM taxpayers;

DROP VIEW IF EXISTS v_ele_withholds cascade;
CREATE VIEW v_ele_withholds AS
    SELECT
        w.id::bigint id,
        w.code,
        w.number,
        '07' AS code_document,
        substr(w.number, 1, 3) AS establishment,
        substr(w.number, 4, 3) AS emission_point,
        substr(w.number, 7, 15) AS sequence,
        w.date,
        w.fiscal_period,
        w.identification_type,
        w.identification,
        w.legal_name,
        w.related,
        (
        SELECT e.address FROM establishments e
        WHERE e.code = substr(w.number, 1, 3)) AS establishment_address,
        w.access_key
    FROM withholds w;

DROP VIEW IF EXISTS v_ele_withholds_detail;
CREATE VIEW v_ele_withholds_detail AS
    SELECT
        d.id::bigint id,
        w.code,
        w.number,
        s.code_support,
        d.line::bigint AS line,
        d.tax_code,
        d.withhold_code,
        d.base_value,
        d.percentage,
        d.withholded_value
    FROM withholds_detail d
    JOIN withholds_support s ON s.id = d.withhold_support_id
    JOIN withholds w ON w.id = s.withhold_id;

DROP VIEW IF EXISTS v_ele_withholds_document_taxes;
CREATE VIEW v_ele_withholds_document_taxes AS
    SELECT
        t.id::bigint id,
        w.code,
        w.number,
        s.code_support,
        t.tax_code,
        t.percentage_code,
        t.tax_base,
        t.tax_iva,
        t.value
    FROM withholds_document_taxes t
    JOIN withholds_support s ON s.id = t.withhold_support_id
    JOIN withholds w ON w.id = s.withhold_id;

DROP VIEW IF EXISTS v_ele_withholds_support;
CREATE VIEW v_ele_withholds_support AS
    SELECT
        s.id::bigint id,
        w.code,
        w.number,
        s.code_support,
        s.code_document_support,
        s.number_document_support,
        s.date_document_support,
        s.authorization_document_support,
        s.total_without_taxes,
        s.total
    FROM withholds_support s
    JOIN withholds w ON w.id = s.withhold_id;

CREATE TABLE IF NOT EXISTS v_users (
    id integer NOT NULL,
    status boolean,
    password character varying(255),
    role character varying(255),
    username character varying(255),
    CONSTRAINT v_users_pkey PRIMARY KEY (id)
);

CREATE OR REPLACE VIEW v_version AS 
    select 1 as id,
    version() as version_database;

INSERT INTO v_users (id,username,password,role,status) 
VALUES (1,'Administrator','sha1:86F7E437FAA5A7FCE15D1DDCB9EAEAEA377667B8','Administrator',true) ON CONFLICT (ID) DO NOTHING;
