CREATE TABLE IF NOT EXISTS ele_documents (
    authorization_date timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    authorization_code character varying(255),
    code character varying(255) NOT NULL,
    number character varying(255) NOT NULL,
    observation character varying(255),
    status character varying(255),
    CONSTRAINT ele_documents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ele_parameters (
    id bigint NOT NULL,    
    name character varying(255),
    value character varying(255),
    observation character varying(255),
    type character varying(255),    
    status boolean DEFAULT true,    
    CONSTRAINT ele_parameters_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v_assets (
    id character varying(255) NOT NULL,
    name character varying(255),
    value character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_credit_notes (
    total numeric(38,2),
    total_without_taxes numeric(38,2),
    date date,
    updated_date_document date,
    id uuid NOT NULL,
    access_key character varying(255),
    address character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    reason character varying(255),
    sequence character varying(255),
    updated_code_document character varying(255),
    updated_number_document character varying(255)
);


CREATE TABLE IF NOT EXISTS v_ele_credit_notes_detail (
    discount numeric(38,2),
    quantity numeric(38,2),
    tax_iva numeric(38,2),
    total_price_without_tax numeric(38,2),
    unit_price numeric(38,2),
    value_iva numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    name character varying(255),
    number character varying(255),
    principal_code character varying(255),
    tax_code character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_debit_notes (
    total numeric(38,2),
    total_without_taxes numeric(38,2),
    date date,
    updated_date_document date,
    id uuid NOT NULL,
    access_key character varying(255),
    address character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    sequence character varying(255),
    updated_code_document character varying(255),
    updated_number_document character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_debit_notes_detail (
    value numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    number character varying(255),
    reason character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_delivery_notes (
    date date,
    date_end_transport date,
    date_start_transport date,
    id uuid NOT NULL,
    access_key character varying(255),
    address_start character varying(255),
    carrier_identification character varying(255),
    carrier_identification_type character varying(255),
    carrier_legal_name character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    number character varying(255),
    observation character varying(255),
    plate character varying(255),
    sequence character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_delivery_notes_receiver (
    date_document_support date,
    line bigint,
    id uuid NOT NULL,
    address character varying(255),
    authorization_document_support character varying(255),
    code character varying(255),
    code_document_support character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    number_document_support character varying(255),
    transfer_reason character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_delivery_notes_receiver_detail (
    quantity numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    name character varying(255),
    number character varying(255),
    principal_code character varying(255)
);

DROP VIEW IF EXISTS v_ele_establishments;
CREATE VIEW v_ele_establishments AS
    SELECT 
        e.id::bigint as id,
        t.identification,
        e.code, 
        e.business_name, 
        e.address,
        CASE 
	        WHEN e.is_principal = true THEN 'Principal'
	        ELSE 'BranchOffice'
    	END AS principal        
    FROM establishments e join taxpayers t
	on t.id = e.taxpayer_id;

CREATE TABLE IF NOT EXISTS v_ele_general_observations (
    id integer NOT NULL,
    name character varying(255),
    value character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_information (
    id integer NOT NULL,
    identification character varying(255),
    name character varying(255),
    value character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_invoices (
    discount numeric(38,2),
    tip numeric(38,2),
    total numeric(38,2),
    total_without_taxes numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    address character varying(255),
    code character varying(255),
    code_document character varying(255),
    delivery_note character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    sequence character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_invoices_detail (
    discount numeric(38,2),
    quantity numeric(38,2),
    tax_iva numeric(38,2),
    total_price_without_tax numeric(38,2),
    unit_price numeric(38,2),
    value_iva numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    name character varying(255),
    number character varying(255),
    principal_code character varying(255),
    tax_code character varying(255),
    unit character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_liquidations (
    discount numeric(38,2),
    total numeric(38,2),
    total_without_taxes numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    address character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    sequence character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_liquidations_detail (
    discount numeric(38,2),
    quantity numeric(38,2),
    tax_iva numeric(38,2),
    total_price_without_tax numeric(38,2),
    unit_price numeric(38,2),
    value_iva numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    name character varying(255),
    number character varying(255),
    principal_code character varying(255),
    tax_code character varying(255),
    unit character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_liquidations_taxes (
    tax_base numeric(38,2),
    tax_iva numeric(38,2),
    value numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    number character varying(255),
    percentage_code character varying(255),
    principal_code character varying(255),
    tax_code character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_payments (
    payment_deadline numeric(38,2),
    total numeric(38,2),
    id uuid NOT NULL,
    code character varying(255),
    name character varying(255),
    number character varying(255),
    unit_time character varying(255),
    way_pay character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_credit_notes (
    total numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_debit_notes (
    total numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_delivery_notes (
    total numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_invoices (
    total numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_liquidations (
    total numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_report_withholds (
    total numeric(38,2),
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    code character varying(255),
    email character varying(255),
    identification character varying(255),
    legal_name character varying(255),
    number character varying(255),
    status character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_taxes_detail (
    tax_base numeric(38,2),
    tax_iva numeric(38,2),
    value numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    number character varying(255),
    percentage_code character varying(255),
    principal_code character varying(255),
    tax_code character varying(255)
);

CREATE OR REPLACE VIEW v_ele_taxpayer AS
    SELECT 
        id, 
        identification, 
        legal_name, 
        forced_accounting, 
        special_taxpayer, 
        retention_agent, 
        rimpe as regime
    FROM taxpayers;

CREATE TABLE IF NOT EXISTS v_ele_withholds (
    date date,
    id uuid NOT NULL,
    access_key character varying(255),
    code character varying(255),
    code_document character varying(255),
    emission_point character varying(255),
    establishment character varying(255),
    establishment_address character varying(255),
    fiscal_period character varying(255),
    identification character varying(255),
    identification_type character varying(255),
    legal_name character varying(255),
    number character varying(255),
    related character varying(255),
    sequence character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_withholds_detail (
    base_value numeric(38,2),
    percentage numeric(38,2),
    withholded_value numeric(38,2),
    line bigint,
    id uuid NOT NULL,
    code character varying(255),
    code_support character varying(255),
    number character varying(255),
    tax_code character varying(255),
    withhold_code character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_withholds_document_taxes (
    tax_base numeric(38,2),
    tax_iva numeric(38,2),
    value numeric(38,2),
    id uuid NOT NULL,
    code character varying(255),
    code_support character varying(255),
    number character varying(255),
    percentage_code character varying(255),
    tax_code character varying(255)
);

CREATE TABLE IF NOT EXISTS v_ele_withholds_support (
    total numeric(38,2),
    total_without_taxes numeric(38,2),
    date_document_support date,
    id uuid NOT NULL,
    authorization_document_support character varying(255),
    code character varying(255),
    code_document_support character varying(255),
    code_support character varying(255),
    number character varying(255),
    number_document_support character varying(255)
);

CREATE TABLE IF NOT EXISTS v_users (
    id integer NOT NULL,
    status boolean,
    password character varying(255),
    role character varying(255),
    username character varying(255)
);

CREATE OR REPLACE VIEW v_version AS 
    select 1 as id,
    version() as version_database;

Insert into ele_parameters (ID,name,value,observation,type) 
values (1,'Base Directory','/app/RoQui','Base directory for files','SRI') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (2,'Certificate','Certificate.p12','Certificate name','Certificate') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (3,'Certificate Password','***************==','Certificate Password','Certificate') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (4,'Logo JPEG','logo.jpeg','URL logo JPEG','SRI') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (5,'Email SMTP Server','localhost','Email SMTP Server','Email SMTP') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (6,'Port Email SMTP Server','1025','Port Email SMTP Server','Email SMTP') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (7,'Email Account','hola@localhost','Account of Email SMTP Server','Email SMTP') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (8,'Email Password Account','','Password Account of Email SMTP Server','Email SMTP') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (9,'Email Encryption','None','Connection Encryption: None, SSL/TLS ','Email SMTP') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (10,'Email HTTP Server','https://mail.server.com','Email HTTP Server','Email HTTP') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (11,'Email HTTP Server Token','**************==','Token Email HTTP Server','Email HTTP') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (12,'Logo PNG','logo.png','URL Logo PNG','Resource') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (13,'Template Email','template.html','URL template','Resource') ON CONFLICT (ID) DO NOTHING;
Insert into ele_parameters (ID,name,value,observation,type) 
values (99,'Subscription','w1b5fZ31Z+8qnlYW0Sa3vA==','Subscription','Subscription') ON CONFLICT (ID) DO NOTHING;