// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoQuiApi.Data;

#nullable disable

namespace RoQuiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoQuiApi.RoQui.Head.Model.Establishmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("address");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("business_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("code");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("principal");

                    b.Property<int>("TaxpayerId")
                        .HasColumnType("integer")
                        .HasColumnName("taxpayer_id");

                    b.HasKey("Id");

                    b.HasIndex("TaxpayerId");

                    b.ToTable("establishments");
                });

            modelBuilder.Entity("RoQuiApi.RoQui.Head.Model.Taxpayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ForcedAccounting")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("forced_accounting");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identification");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("legal_name");

                    b.Property<string>("RetentionAgent")
                        .HasColumnType("varchar")
                        .HasColumnName("retention_agent");

                    b.Property<string>("Rimpe")
                        .HasColumnType("varchar")
                        .HasColumnName("rimpe");

                    b.Property<string>("SpecialTaxpayer")
                        .HasColumnType("varchar")
                        .HasColumnName("special_taxpayer");

                    b.HasKey("Id");

                    b.ToTable("taxpayers");
                });

            modelBuilder.Entity("RoQuiApi.RoQui.Invoice.Model.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("access_key");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DeliveryNote")
                        .HasColumnType("varchar")
                        .HasColumnName("delivery_note");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identification");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identification_type");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("legal_name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("RoQuiApi.RoQui.Invoice.Model.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal")
                        .HasColumnName("discount");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Line")
                        .HasColumnType("int")
                        .HasColumnName("line");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal")
                        .HasColumnName("quantity");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("tax_code");

                    b.Property<decimal>("TaxIva")
                        .HasColumnType("decimal")
                        .HasColumnName("tax_iva");

                    b.Property<decimal>("TotalPriceWithoutTax")
                        .HasColumnType("decimal")
                        .HasColumnName("total_price_without_tax");

                    b.Property<string>("Unit")
                        .HasColumnType("varchar")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal")
                        .HasColumnName("unit_price");

                    b.Property<decimal>("ValueIva")
                        .HasColumnType("decimal")
                        .HasColumnName("value_iva");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_details");
                });

            modelBuilder.Entity("RoQuiApi.RoQui.Head.Model.Establishmet", b =>
                {
                    b.HasOne("RoQuiApi.RoQui.Head.Model.Taxpayer", "Taxpayer")
                        .WithMany("Establishments")
                        .HasForeignKey("TaxpayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxpayer");
                });

            modelBuilder.Entity("RoQuiApi.RoQui.Invoice.Model.InvoiceDetail", b =>
                {
                    b.HasOne("RoQuiApi.RoQui.Invoice.Model.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("RoQuiApi.RoQui.Head.Model.Taxpayer", b =>
                {
                    b.Navigation("Establishments");
                });

            modelBuilder.Entity("RoQuiApi.RoQui.Invoice.Model.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
