// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoQuiApi.Data;

#nullable disable

namespace RoQuiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoQuiApi.RoQui.Head.Model.Taxpayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ForcedAccounting")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("forced_accounting");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identification");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("legal_name");

                    b.Property<string>("RetentionAgent")
                        .HasColumnType("varchar")
                        .HasColumnName("retention_agent");

                    b.Property<string>("Rimpe")
                        .HasColumnType("varchar")
                        .HasColumnName("rimpe");

                    b.Property<string>("SpecialTaxpayer")
                        .HasColumnType("varchar")
                        .HasColumnName("special_taxpayer");

                    b.HasKey("Id");

                    b.ToTable("taxpayers");
                });
#pragma warning restore 612, 618
        }
    }
}
